public enum PAGE_TYPE
{
     PAGE_TYPE_TEXT = 0,
     PAGE_TYPE_IMG = 1,
     PAGE_TYPE_BUTTON = 2,
     PAGE_TYPE_GET_ITEM = 3,
     PAGE_TYPE_STATUS = 4,
     PAGE_TYPE_RECURSIVE_GROUP = 5,
     PAGE_TYPE_BATTLE = 6,
}
public enum OCCUR_CONDITION
{
     OCCUR_CONDITION_OWN_ITEM = 0,
     OCCUR_CONDITION_STATUS_HIGH = 1,
     OCCUR_CONDITION_STATUS_LOW = 2,
     OCCUR_CONDITION_PAGE_VIEWED = 3,
     OCCUR_CONDITION_NOT_ENOUGH_OWN_ITEM = 4,
}
public enum ITEM_TYPE
{
     ITEM_TYPE_NORMAL = 0,
     ITEM_TYPE_EQUIP_WEAPON = 1,
     ITEM_TYPE_EQUIP_HEAD = 2,
     ITEM_TYPE_EQUIP_ARMOR = 3,
     ITEM_TYPE_EQUIP_SHOES = 4,
     ITEM_TYPE_EQUIP_RING = 5,
     ITEM_TYPE_EQUIP_NECKLACE = 6,
}
public enum ITEM_FUNCTION_TYPE
{
     ITEM_FUNCTION_TYPE_CHAGE_STATUS = 0,
     ITEM_FUNCTION_TYPE_MOVE_PAGE = 1,
     ITEM_FUNCTION_TYPE_EQUIP = 2,
}
public enum STATUS_FUNCTION_TYPE
{
     STATUS_FUNCTION_TYPE_MAX_STAT = 0,
     STATUS_FUNCTION_TYPE_GET_STAT = 1,
}
public enum ACTION_TYPE
{
     ACTION_TYPE_NORMAL_ATTACK = 0,
     ACTION_TYPE_SPECIAL_ATTACK = 1,
     ACTION_TYPE_DODGE = 2,
     ACTION_TYPE_BUFF = 3,
     ACTION_TYPE_DEBUFF = 4,
     ACTION_TYPE_ACTION_CANCEL = 5,
}
public enum ACH_TYPE
{
     ACH_TYPE_PAGE_VIEW = 0,
     ACH_TYPE_OWN_ITEM = 1,
     ACH_TYPE_KILL_MONSTER = 2,
     ACH_TYPE_DEAD_COUNT = 3,
}
public enum CONTENT_TYPE
{
     CONTENT_TYPE_ITEM = 0,
     CONTENT_TYPE_STATUS = 1,
     CONTENT_TYPE_ACHIEVEMENT = 2,
     CONTENT_TYPE_COLLECTION = 3,
}

public enum ACTION_RESULT_TYPE
{
     
     
}